#!/usr/bin/env python3
"""Version from git: v1.2.3 -> 1.2.3, v1.2.3-5-gabc1234 -> 1.2.3+5.gabc1234,
no tag -> 0.0.0+g<sha>, no git -> 0.0.0.

Single Python source of the derivation, shared by this CLI and conanfile.py.
cmake/nanofix-version.cmake implements the same rules in pure CMake (configure
must work with no shell or Python installed); CI's `version` job cross-checks
the two. The header text has one source for both: cmake/version.hpp.in.

The real header is generated by CMake into the build tree
(<build>/nanofix-generated/include/nanofix/detail/version.hpp); the committed
include/nanofix/detail/version.hpp is a 0.0.0+unknown stub and is never
written by this script. $NANOFIX_VERSION_OVERRIDE wins over git (CLI only).

  gen_version.py --print           print the version
  gen_version.py --check <header>  fail if <header> does not match git
  gen_version.py <output>          write the header to <output>
"""

import os
import re
import subprocess
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_TEMPLATE = os.path.join(_ROOT, "cmake", "version.hpp.in")


def git_version(root):
    def _git(*args):
        return subprocess.run(
            ("git", "-C", root) + args,
            capture_output=True, text=True, check=True,
        ).stdout.strip()

    try:
        desc = _git("describe", "--tags", "--match", "v[0-9]*")
        version = desc[1:]  # drop the leading v
        if "-" in version:  # v1.2.3-5-gabc1234 -> 1.2.3+5.gabc1234
            base, n, ghash = version.rsplit("-", 2)
            version = f"{base}+{n}.{ghash}"
        return version
    except (subprocess.CalledProcessError, OSError):
        pass
    try:
        return "0.0.0+g" + _git("rev-parse", "--short", "HEAD")
    except (subprocess.CalledProcessError, OSError):
        return "0.0.0"


def render_header(full, template_path=_TEMPLATE):
    """Substitute the @VAR@s of cmake/version.hpp.in exactly like
    configure_file(@ONLY) does, so the two outputs stay byte-identical."""
    m = re.match(r"(\d+)\.(\d+)\.(\d+)", full)
    if not m:
        raise ValueError(f"nanofix: cannot parse version '{full}'")
    with open(template_path, encoding="utf-8") as f:
        text = f.read()
    for key, value in (
        ("NANOFIX_VERSION_MAJOR", m.group(1)),
        ("NANOFIX_VERSION_MINOR", m.group(2)),
        ("NANOFIX_VERSION_PATCH", m.group(3)),
        ("NANOFIX_VERSION_FULL", full),
    ):
        text = text.replace(f"@{key}@", value)
    return text


def main(argv):
    override = os.environ.get("NANOFIX_VERSION_OVERRIDE")
    full = override or git_version(_ROOT)
    if not override and full.startswith("0.0.0+g"):
        print(f"warning: no reachable v* tag; version {full}", file=sys.stderr)

    arg = argv[1] if len(argv) > 1 else ""
    if arg == "--print":
        print(full)
        return 0
    if arg == "--check":
        if len(argv) < 3:
            print("usage: gen_version.py --check <header>", file=sys.stderr)
            return 2
        header = argv[2]
        if not os.path.isfile(header):
            print(f"error: {header} missing; run a CMake configure first",
                  file=sys.stderr)
            return 1
        with open(header, encoding="utf-8") as f:
            on_disk = f.read()
        expected = render_header(full)
        if on_disk != expected:
            sys.stderr.write(f"error: {header} does not match git describe\n"
                             f"--- expected\n{expected}"
                             f"--- on disk\n{on_disk}")
            return 1
        print(f"{header} in sync with git ({full})")
        return 0
    if arg:
        with open(arg, "w", encoding="utf-8", newline="\n") as f:
            f.write(render_header(full))
        print(f"wrote {arg} ({full})")
        return 0
    print("usage: gen_version.py --print | --check <header> | <output>",
          file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
